### ISSUE TITLE
Log the delete request (with matchers) instead of tombstones.

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/tsdb#133]
Currently we are writing the series that are affected and their time-ranges to the WAL. But I think we can simplify WAL by logging the delete request instead of the tombstones without losing anything. 

The advantage is that we will know what the delete request was instead of opaque tombstones.

@fabxc Your thoughts?

**Comment by fabxc** [comment]
Mh, what problem's would it solve though?

 It would certainly be the more complex disk format as it introduces concepts of the query mechanism to the serialization. `IndexWriter` and `ChunkWriter` don't know anything about matchers at this point for example.
Also, `Matcher`s are an interface and people can implement their own on the client side. If we made it part the the format, it would be fixed to what we currently have. I know custom matchers are somewhat unlikely, but still kinda nice in theory.

If size of the tombstone files was an issue I would consider it, but they are small and deleted eventually anyway.

Lastly, when loading blocks, we would have to re-apply the deletes all the time and have tombstones in memory again. We can only efficiently consider deletions at query time with the tombstone intervals. Otherwise, we'd have to re-evaluate every delete request on every query.

**Comment by Gouthamve** [comment]
Hmm, I see that Matcher being an interface doesn't really allow for this. Closing.
