### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by telendt** [prometheus/tsdb#48]
This project does not vendor its dependencies, so I had to `go get` them manually.

But when I tried to run tests I got the following.
```
$ go test
# github.com/prometheus/tsdb
head_test.go:26:2: cannot find package "github.com/prometheus/prometheus/pkg/labels" in any of:
	/usr/local/go/src/github.com/prometheus/prometheus/pkg/labels (from $GOROOT)
	/Users/telendt/goprojects/src/github.com/prometheus/prometheus/pkg/labels (from $GOPATH)
FAIL	github.com/prometheus/tsdb [setup failed]
```

If I switch `github.com/prometheus/prometheus` to dev-2.0, I get:

```
$ go test
# github.com/prometheus/tsdb
./compact.go:60: undefined: prometheus.Registerer
./compact.go:90: undefined: prometheus.Registerer
./db.go:133: undefined: prometheus.Registerer
./db.go:155: undefined: prometheus.Registerer
FAIL	github.com/prometheus/tsdb [build failed]
```

What's the prometheus version you test it against?

**Comment by Gouthamve** [comment]
Hmm, so I am able run `go test` successfully (`prometheus/promtheus` checked out to dev-2.0) and the error you are getting is due to the client_golang lib. 

Can you upgrade `github.com/prometheus/client_golang/prometheus` by running `go get -u github.com/prometheus/client_golang/prometheus` and try again?

**Comment by telendt** [comment]
@Gouthamve thanks, that helped.
