### ISSUE TITLE
Why do Max and Minn have opposite definitions?

### ISSUE THREAD

**Issue by jeasonWujun** [prometheus/tsdb#557]
tsdb/head.go

```
func (h *Head) processWALSamples(
	minValidTime int64,
	input <-chan []RefSample, output chan<- []RefSample,
) (unknownRefs uint64) {
	defer close(output)

	// Mitigate lock contention in getByID.
	refSeries := map[uint64]*memSeries{}

	mint, maxt := int64(math.MaxInt64), int64(math.MinInt64)
```

**Comment by krasi-georgiev** [comment]
yeah it is a bit awkward, but this is so that some parts of the code assume that when `mint == math.MaxInt64` it is considered as NOT set. The same for `maxt == math.MinInt64`.

for example: 
https://github.com/prometheus/tsdb/blob/99703b3269a1b870e04524e97b807319e1540720/head.go#L672

Could you please ask dev questions in #prometheus-dev channel as we use github for tracking issues and new feature requests.

feel free to ping me directly
